const SUPABASE_URL='https://slsiwqvbdcdcgrkufsln.supabase.co';
const SUPABASE_KEY='sb_publishable_dtWiemrqMQHEXN5SGLGnPw_VGs-ottO';
const SB=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=id=>document.getElementById(id); let profile=null,employees=[],attendance=[],summary={};
const emailFor=u=>u.includes('@')?u:`${u.toLowerCase()}@login.leeway.local`;
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const canAll=()=>!!profile&&(profile.role==='admin'||profile.can_view_all);
async function fn(name,body){const {data,error}=await SB.functions.invoke(name,{body});if(error)throw new Error(error.message);if(data?.error)throw new Error(data.error);return data}
function visibleEmployees(){return employees}
function score(s){return ({P:4,LC:3,HD:2,A:1,NP:0}[s||'NP'])}
function statusClass(s){return `<span class="status ${esc(s||'NP')}">${esc(s||'NP')}</span>`}
function dashboard(){const list=visibleEmployees();return `<div class="hero"><div><div class="eyebrow">OVERVIEW</div><h3>Good to see you, ${esc(profile.display_name||profile.username)}</h3><div class="muted">Live workforce and attendance snapshot.</div></div></div><div class="cards"><div class="card"><div class="metric-label">VISIBLE EMPLOYEES</div><div class="metric">${summary.employees??list.length}</div></div><div class="card"><div class="metric-label">PRESENT</div><div class="metric">${summary.present??0}</div></div><div class="card"><div class="metric-label">LATE / HALFDAY</div><div class="metric">${(summary.late||0)+(summary.halfday||0)}</div></div><div class="card"><div class="metric-label">ABSENT / NP</div><div class="metric">${(summary.absent||0)+(summary.np||0)}</div></div></div><div class="section"><div class="section-title">Workforce</div>${list.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Employee</th><th>Code</th><th>Designation</th><th>Circle</th><th>Reporting</th></tr></thead><tbody>${list.slice(0,20).map(e=>`<tr><td><strong>${esc(e.employee_name)}</strong></td><td>${esc(e.employee_code)}</td><td>${esc(e.designation||'—')}</td><td>${esc(e.circle||'—')}</td><td>${esc(e.manager_employee_code||e.team_leader_employee_code||'—')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="notice">Upload Employee Master CSV to start.</div>'}</div>`}
function attendancePage(){const list=visibleEmployees();return `<div class="hero"><div><div class="eyebrow">ATTENDANCE</div><h3>Monthly Attendance</h3><div class="muted">Click an employee to see date-wise final status, BIO and TOS.</div></div></div><div class="toolbar"><input id="employeeSearch" placeholder="Search employee"><input id="attendanceMonth" type="month" value="${new Date().toISOString().slice(0,7)}"></div><div id="attendanceTable">${attendanceTable(list)}</div>`}
function attendanceTable(list){return list.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Employee</th><th>Code</th><th>Designation</th><th>Month</th><th>Action</th></tr></thead><tbody>${list.map(e=>`<tr><td><strong>${esc(e.employee_name)}</strong></td><td>${esc(e.employee_code)}</td><td>${esc(e.designation||'—')}</td><td>${attendance.filter(a=>a.employee_code===e.employee_code).length} records</td><td><button class="primary calendar-btn" data-code="${esc(e.employee_code)}">Open Calendar</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="notice">No employees visible.</div>'}
function employeeCalendar(code){const e=employees.find(x=>x.employee_code===code);const rows=attendance.filter(a=>a.employee_code===code).sort((a,b)=>String(a.attendance_date).localeCompare(String(b.attendance_date)));return `<div class="section"><button class="ghost" id="backAttendance">← Back</button><div class="hero"><div><div class="eyebrow">EMPLOYEE ATTENDANCE</div><h3>${esc(e?.employee_name||code)}</h3><div class="muted">${esc(code)} · click a date row to inspect source values.</div></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Date</th><th>Final</th><th>BIO</th><th>TOS</th></tr></thead><tbody>${rows.length?rows.map(r=>`<tr class="att-row" data-date="${esc(r.attendance_date)}"><td>${esc(r.attendance_date)}</td><td>${statusClass(r.final_status)}</td><td>${statusClass(r.bio_status)}</td><td>${statusClass(r.tos_status)}</td></tr>`).join(''):'<tr><td colspan="4">No attendance for selected month.</td></tr>'}</tbody></table></div><div id="attendanceDetail" class="section"></div></div>`}
async function detailAttendance(code,date){const [{data:b},{data:t}]=await Promise.all([SB.from('hrms_bio_attendance').select('*').eq('employee_code',code).eq('attendance_date',date).maybeSingle(),SB.from('hrms_tos_attendance').select('*').eq('employee_code',code).eq('attendance_date',date).maybeSingle()]);$('attendanceDetail').innerHTML=`<div class="cards"><div class="card"><div class="metric-label">BIO · ${esc(date)}</div><div class="section-title">IN: ${esc(b?.in_time||'—')} &nbsp; OUT: ${esc(b?.out_time||'—')}</div><div>Work: ${esc(b?.work_minutes??'—')} minutes · ${statusClass(b?.status)}</div></div><div class="card"><div class="metric-label">TOS</div><div class="section-title">Login: ${esc(t?.login_minutes??'—')} min</div><div>Effective: ${esc(t?.effective_minutes??'—')} minutes · ${statusClass(t?.status)}</div></div></div>`}
function employeesPage(){const list=visibleEmployees();return `<div class="hero"><div><div class="eyebrow">PEOPLE</div><h3>Employee Master</h3><div class="muted">Identity, hierarchy, shift and BIO/TOS mapping.</div></div></div>${list.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Name</th><th>Code</th><th>Designation</th><th>Circle</th><th>BIO ID</th><th>TOS ID</th><th>Shift</th></tr></thead><tbody>${list.map(e=>`<tr><td><strong>${esc(e.employee_name)}</strong></td><td>${esc(e.employee_code)}</td><td>${esc(e.designation||'—')}</td><td>${esc(e.circle||'—')}</td><td>${esc(e.bio_id||'—')}</td><td>${esc(e.tos_id||'—')}</td><td>${esc(e.shift_in||'—')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="notice">No employee master uploaded yet.</div>'}`}
function reports(){const by={P:0,LC:0,HD:0,A:0,NP:0};attendance.forEach(x=>by[x.final_status]=(by[x.final_status]||0)+1);return `<div class="hero"><div><div class="eyebrow">ANALYTICS</div><h3>MIS Reports</h3><div class="muted">Current loaded attendance summary.</div></div></div><div class="cards">${['P','LC','HD','A','NP'].map(s=>`<div class="card"><div class="metric-label">${s==='P'?'PRESENT':s==='LC'?'LATE':s==='HD'?'HALFDAY':s==='A'?'ABSENT':'NOT PUNCHED'}</div><div class="metric">${by[s]}</div></div>`).join('')}</div><div class="section"><button id="exportReport" class="primary">Export Current Attendance CSV</button></div>`}
function uploadPage(){return `<div class="hero"><div><div class="eyebrow">DATA INPUT</div><h3>CSV Upload</h3><div class="muted">Employee Master first, then BIO and TOS files.</div></div></div><div class="cards"><div class="card"><div class="section-title">1. Employee Master</div><input id="empFile" type="file" accept=".csv"><button class="primary upload-btn" data-type="employees" data-file="empFile">Upload Employee CSV</button></div><div class="card"><div class="section-title">2. BIO Attendance</div><input id="bioFile" type="file" accept=".csv"><button class="primary upload-btn" data-type="bio" data-file="bioFile">Upload BIO CSV</button></div><div class="card"><div class="section-title">3. TOS Attendance</div><input id="tosFile" type="file" accept=".csv"><button class="primary upload-btn" data-type="tos" data-file="tosFile">Upload TOS CSV</button></div></div><div id="uploadResult" class="section"></div>`}
function usersPage(){return `<div class="hero"><div><div class="eyebrow">ADMINISTRATION</div><h3>User Management</h3><div class="muted">Create users and control role-based access.</div></div></div><div class="card"><div class="section-title">Create User</div><div class="toolbar"><input id="uUsername" placeholder="Username"><input id="uEmail" placeholder="Email"><input id="uPassword" type="password" placeholder="Password (min 6)"><input id="uName" placeholder="Display name"><select id="uRole"><option value="viewer">MIS / Viewer</option><option value="manager">Manager</option><option value="team_leader">Team Leader</option><option value="tele_sales_executive">Tele Sales Executive</option><option value="uploader">Uploader</option><option value="admin">Admin</option></select><button id="createUser" class="primary">Create User</button></div></div><div id="usersList" class="section"></div>`}
function parseCSV(text){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(x=>x.trim());if(lines.length<2)return[];const parse=l=>{const a=[];let q=false,c='',i=0;for(;i<l.length;i++){const ch=l[i];if(ch==='"'){if(q&&l[i+1]==='"'){c+='"';i++}else q=!q}else if(ch===','&&!q){a.push(c.trim());c=''}else c+=ch}a.push(c.trim());return a};const h=parse(lines[0]);return lines.slice(1).map(l=>{const v=parse(l),o={};h.forEach((k,i)=>o[k]=v[i]??'');return o})}
async function doUpload(type,file){const rows=parseCSV(await file.text());if(!rows.length)throw new Error('CSV has no data rows');const result=await fn('hrms-upload',{type,rows,source_file:file.name});$('uploadResult').innerHTML=`<div class="notice"><strong>${esc(type.toUpperCase())} uploaded.</strong> Accepted: ${result.accepted??result.inserted??0} · Skipped: ${result.skipped??0} · Finalized: ${result.finalized??0}</div>`;await loadData()}
async function loadUsers(){const r=await fn('hrms-admin',{action:'list'});$('usersList').innerHTML=`<div class="table-wrap"><table class="table"><thead><tr><th>Username</th><th>Name</th><th>Role</th><th>Employee Code</th><th>Status</th></tr></thead><tbody>${r.data.map(u=>`<tr><td>${esc(u.username)}</td><td>${esc(u.display_name)}</td><td>${esc(u.role)}</td><td>${esc(u.employee_code||'—')}</td><td>${u.active?'Active':'Inactive'}</td></tr>`).join('')}</tbody></table></div>`}
async function loadData(){const month=new Date().toISOString().slice(0,7);const r=await fn('hrms-dashboard',{month});profile=r.profile;employees=r.employees||[];attendance=r.attendance||[];summary=r.summary||{}}
async function boot(){const {data:{session}}=await SB.auth.getSession();if(!session){$('loginView').classList.remove('hidden');$('appView').classList.add('hidden');return}try{await loadData();if(!profile?.active)throw Error('Profile unavailable');$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');$('roleBadge').textContent=profile.role.replaceAll('_',' ').toUpperCase();$('profileMini').innerHTML=`<strong>${esc(profile.display_name)}</strong><small class="muted">${esc(profile.designation||profile.role)}</small>`;$('today').textContent=new Date().toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'});document.querySelectorAll('.admin-only').forEach(x=>x.classList.toggle('hidden',!(profile.role==='admin'||profile.can_upload)));render('dashboard')}catch(e){await SB.auth.signOut();$('loginError').textContent=e.message||'Unable to load HRMS profile.'}}
function render(page){const titles={dashboard:'Dashboard',attendance:'Attendance',employees:'Employees',reports:'MIS Reports',upload:'Data Upload',users:'User Management'};$('pageTitle').textContent=titles[page]||'Dashboard';document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===page));const views={dashboard,attendance:attendancePage,employees:employeesPage,reports,upload:uploadPage,users:usersPage};$('content').innerHTML=(views[page]||dashboard)();if(page==='attendance')bindAttendance();if(page==='reports')$('exportReport').onclick=exportCSV;if(page==='upload')bindUpload();if(page==='users')bindUsers()}
function bindAttendance(){const search=$('employeeSearch');search.oninput=()=>{$('attendanceTable').innerHTML=attendanceTable(employees.filter(e=>JSON.stringify(e).toLowerCase().includes(search.value.toLowerCase())));bindAttendanceButtons()};bindAttendanceButtons()}
function bindAttendanceButtons(){document.querySelectorAll('.calendar-btn').forEach(b=>b.onclick=()=>{const code=b.dataset.code;$('content').innerHTML=employeeCalendar(code);$('backAttendance').onclick=()=>render('attendance');document.querySelectorAll('.att-row').forEach(r=>r.onclick=()=>detailAttendance(code,r.dataset.date))})}
function bindUpload(){document.querySelectorAll('.upload-btn').forEach(b=>b.onclick=async()=>{const f=$(b.dataset.file).files[0];if(!f){$('uploadResult').innerHTML='<div class="notice">Please select a CSV file.</div>';return}b.disabled=true;try{await doUpload(b.dataset.type,f)}catch(e){$('uploadResult').innerHTML=`<div class="notice">Upload failed: ${esc(e.message)}</div>`}b.disabled=false})}
function bindUsers(){$('createUser').onclick=async()=>{try{await fn('hrms-admin',{action:'create',username:$('uUsername').value,email:$('uEmail').value,password:$('uPassword').value,display_name:$('uName').value,role:$('uRole').value});await loadUsers();alert('User created successfully.')}catch(e){alert(e.message)}};loadUsers().catch(e=>{$('usersList').innerHTML=`<div class="notice">${esc(e.message)}</div>`})}
function exportCSV(){const head=['Employee Code','Date','BIO','TOS','Final'];const rows=attendance.map(x=>[x.employee_code,x.attendance_date,x.bio_status||'',x.tos_status||'',x.final_status]);const csv=[head,...rows].map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='hrms-attendance.csv';a.click();URL.revokeObjectURL(a.href)}
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();const btn=$('loginBtn');$('loginError').textContent='';btn.disabled=true;btn.textContent='Signing in…';const {error}=await SB.auth.signInWithPassword({email:emailFor($('username').value.trim()),password:$('password').value});if(error)$('loginError').textContent=error.message||'Invalid username or password.';else await boot();btn.disabled=false;btn.textContent='Sign in'});$('logoutBtn').addEventListener('click',async()=>{await SB.auth.signOut();location.reload()});document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>render(b.dataset.page)));SB.auth.onAuthStateChange((event)=>{if(event==='SIGNED_OUT')location.reload()});boot();