const SUPABASE_URL='https://slsiwqvbdcdcgrkufsln.supabase.co';
const SUPABASE_KEY='sb_publishable_dtWiemrqMQHEXN5SGLGnPw_VGs-ottO';
const SB=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=id=>document.getElementById(id); let profile=null,employees=[],attendance=[],summary={};
const emailFor=u=>{u=String(u||'').trim().toLowerCase();return u==='admin'?'srp8046@gmail.com':(u.includes('@')?u:`${u}@login.leeway.local`)};
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function fn(name,body){const {data,error}=await SB.functions.invoke(name,{body});if(error)throw new Error(error.message);if(data?.error)throw new Error(data.error);return data}
function score(s){return ({P:4,LC:3,HD:2,A:1,NP:0}[s||'NP'])}
function statusClass(s){return `<span class="status ${esc(s||'NP')}">${esc(s||'NP')}</span>`}
function dashboard(){const list=employees;return `<div class="hero"><div><div class="eyebrow">OVERVIEW</div><h3>Good to see you, ${esc(profile.display_name||profile.username)}</h3><div class="muted">Live workforce and attendance snapshot.</div></div></div><div class="cards"><div class="card"><div class="metric-label">EMPLOYEES</div><div class="metric">${summary.employees??list.length}</div></div><div class="card"><div class="metric-label">PRESENT</div><div class="metric">${summary.present??0}</div></div><div class="card"><div class="metric-label">LATE / HALFDAY</div><div class="metric">${(summary.late||0)+(summary.halfday||0)}</div></div><div class="card"><div class="metric-label">ABSENT / NP</div><div class="metric">${(summary.absent||0)+(summary.np||0)}</div></div></div><div class="section"><div class="section-title">Workforce</div>${list.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Employee</th><th>Code</th><th>Designation</th><th>Circle</th><th>Reporting</th></tr></thead><tbody>${list.slice(0,20).map(e=>`<tr><td><strong>${esc(e.employee_name)}</strong></td><td>${esc(e.employee_code)}</td><td>${esc(e.designation||'—')}</td><td>${esc(e.circle||'—')}</td><td>${esc(e.manager_employee_code||e.team_leader_employee_code||'—')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="notice">Upload Employee Master CSV to start.</div>'}</div>`}
function attendancePage(){return `<div class="hero"><div><div class="eyebrow">ATTENDANCE</div><h3>Monthly Attendance</h3><div class="muted">BIO + TOS final attendance by employee and date.</div></div></div><div class="toolbar"><input id="employeeSearch" placeholder="Search employee"></div><div id="attendanceTable">${attendanceTable(employees)}</div>`}
function attendanceTable(list){return list.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Employee</th><th>Code</th><th>Designation</th><th>Records</th><th>Action</th></tr></thead><tbody>${list.map(e=>`<tr><td><strong>${esc(e.employee_name)}</strong></td><td>${esc(e.employee_code)}</td><td>${esc(e.designation||'—')}</td><td>${attendance.filter(a=>a.employee_code===e.employee_code).length}</td><td><button class="primary calendar-btn" data-code="${esc(e.employee_code)}">Open Calendar</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="notice">No employees visible.</div>'}
function employeeCalendar(code){const e=employees.find(x=>x.employee_code===code);const rows=attendance.filter(a=>a.employee_code===code).sort((a,b)=>String(a.attendance_date).localeCompare(String(b.attendance_date)));return `<div class="section"><button class="ghost" id="backAttendance">← Back</button><div class="hero"><div><div class="eyebrow">EMPLOYEE ATTENDANCE</div><h3>${esc(e?.employee_name||code)}</h3><div class="muted">${esc(code)} · click a date for BIO/TOS detail.</div></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Date</th><th>Final</th><th>BIO</th><th>TOS</th></tr></thead><tbody>${rows.length?rows.map(r=>`<tr class="att-row" data-date="${esc(r.attendance_date)}"><td>${esc(r.attendance_date)}</td><td>${statusClass(r.final_status)}</td><td>${statusClass(r.bio_status)}</td><td>${statusClass(r.tos_status)}</td></tr>`).join(''):'<tr><td colspan="4">No attendance records.</td></tr>'}</tbody></table></div><div id="attendanceDetail" class="section"></div></div>`}
async function detailAttendance(code,date){const [{data:b},{data:t}]=await Promise.all([SB.from('hrms_bio_attendance').select('*').eq('employee_code',code).eq('attendance_date',date).maybeSingle(),SB.from('hrms_tos_attendance').select('*').eq('employee_code',code).eq('attendance_date',date).maybeSingle()]);$('attendanceDetail').innerHTML=`<div class="cards"><div class="card"><div class="metric-label">BIO · ${esc(date)}</div><div class="section-title">IN: ${esc(b?.in_time||'—')} · OUT: ${esc(b?.out_time||'—')}</div><div>Work: ${esc(b?.work_minutes??'—')} min · ${statusClass(b?.status)}</div></div><div class="card"><div class="metric-label">TOS</div><div class="section-title">Login: ${esc(t?.login_minutes??'—')} min</div><div>Effective: ${esc(t?.effective_minutes??'—')} min · ${statusClass(t?.status)}</div></div></div>`}
function employeesPage(){return `<div class="hero"><div><div class="eyebrow">PEOPLE</div><h3>Employee Master</h3><div class="muted">Actual Employee Master mappings.</div></div></div>${employees.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Name</th><th>Code</th><th>Designation</th><th>Supervisor</th><th>Agent ID</th><th>Shift In</th></tr></thead><tbody>${employees.map(e=>`<tr><td><strong>${esc(e.employee_name)}</strong></td><td>${esc(e.employee_code)}</td><td>${esc(e.designation||'—')}</td><td>${esc(e.manager_employee_code||e.team_leader_employee_code||'—')}</td><td>${esc(e.tos_id||'—')}</td><td>${esc(e.shift_in||'—')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="notice">No employee master uploaded yet.</div>'}`}
function reports(){const by={P:0,LC:0,HD:0,A:0,NP:0};attendance.forEach(x=>by[x.final_status]=(by[x.final_status]||0)+1);return `<div class="hero"><div><div class="eyebrow">ANALYTICS</div><h3>MIS Reports</h3><div class="muted">Loaded final attendance records.</div></div></div><div class="cards">${['P','LC','HD','A','NP'].map(s=>`<div class="card"><div class="metric-label">${s==='P'?'PRESENT':s==='LC'?'LATE':s==='HD'?'HALFDAY':s==='A'?'ABSENT':'NOT PUNCHED'}</div><div class="metric">${by[s]}</div></div>`).join('')}</div><div class="section"><button id="exportReport" class="primary">Export Current Attendance CSV</button></div>`}
function uploadPage(){return `<div class="hero"><div><div class="eyebrow">DATA INPUT</div><h3>CSV / Excel Upload</h3><div class="muted">These three source formats are supported: Employee Master CSV, BIO August XLS/XLSX, TOS closing CSV.</div></div></div><div class="cards"><div class="card"><div class="section-title">1. Employee Master</div><input id="empFile" type="file" accept=".csv"><button class="primary upload-btn" data-type="employees" data-file="empFile">Upload Employee Master</button></div><div class="card"><div class="section-title">2. BIO Attendance</div><input id="bioFile" type="file" accept=".xls,.xlsx,.csv"><button class="primary upload-btn" data-type="bio" data-file="bioFile">Upload BIO</button></div><div class="card"><div class="section-title">3. TOS Attendance</div><input id="tosFile" type="file" accept=".csv"><button class="primary upload-btn" data-type="tos" data-file="tosFile">Upload TOS</button></div></div><div id="uploadResult" class="section"></div>`}
function usersPage(){return `<div class="hero"><div><div class="eyebrow">ADMINISTRATION</div><h3>User Management</h3><div class="muted">Create users and control role-based access.</div></div></div><div class="card"><div class="section-title">Create User</div><div class="toolbar"><input id="uUsername" placeholder="Username"><input id="uEmail" placeholder="Email"><input id="uPassword" type="password" placeholder="Password (min 6)"><input id="uName" placeholder="Display name"><select id="uRole"><option value="viewer">MIS / Viewer</option><option value="manager">Manager</option><option value="team_leader">Team Leader</option><option value="tele_sales_executive">Tele Sales Executive</option><option value="uploader">Uploader</option><option value="admin">Admin</option></select><button id="createUser" class="primary">Create User</button></div></div><div id="usersList" class="section"></div>`}
function parseCSV(text){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(x=>x.trim());if(lines.length<2)return[];const parse=l=>{const a=[];let q=false,c='';for(let i=0;i<l.length;i++){const ch=l[i];if(ch==='"'){if(q&&l[i+1]==='"'){c+='"';i++}else q=!q}else if(ch===','&&!q){a.push(c.trim());c=''}else c+=ch}a.push(c.trim());return a};const h=parse(lines[0]);return lines.slice(1).map(l=>{const v=parse(l),o={};h.forEach((k,i)=>o[k]=v[i]??'');return o})}
function excelTime(v){if(v==null||v==='')return'';if(typeof v==='number'){const total=Math.round(v*1440);return `${String(Math.floor(total/60)%24).padStart(2,'0')}:${String(total%60).padStart(2,'0')}:00`}return String(v).trim()}
function parseBioWorkbook(data){const wb=XLSX.read(data,{type:'array',cellDates:true});const rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{header:1,defval:''});let ym='2026-08';const period=rows.slice(0,8).flat().join(' ');const pm=period.match(/(\d{1,2})-([A-Za-z]{3})-(\d{4})/);if(pm){const months={Jan:'01',Feb:'02',Mar:'03',Apr:'04',May:'05',Jun:'06',Jul:'07',Aug:'08',Sep:'09',Oct:'10',Nov:'11',Dec:'12'};ym=`${pm[3]}-${months[pm[2]]||'08'}`}const out=[];for(let i=0;i<rows.length;i++){const r=rows[i];const label=String(r[1]??'').trim().toLowerCase();if(label!=='employee code:-')continue;let code='';for(const v of r){if(String(v).trim() && String(v).trim().toLowerCase()!=='employee code:-'){code=String(v).trim();break} }if(!code)continue;const dates=rows[i+1]||[], statuses=rows[i+2]||[], ins=rows[i+3]||[], outs=rows[i+4]||[];for(let c=2;c<dates.length;c++){const ds=String(dates[c]||'').trim();const dm=ds.match(/^(\d{1,2})-/);if(!dm)continue;const day=String(Number(dm[1])).padStart(2,'0');out.push({"employee_code":code,"attendance_date":`${ym}-${day}`,"in_time":excelTime(ins[c]),"out_time":excelTime(outs[c]),"status_source":String(statuses[c]||'').trim()})}}return out}
async function readUpload(file,type){const data=await file.arrayBuffer();if(type==='bio')return parseBioWorkbook(data);return parseCSV(new TextDecoder().decode(data))}
async function doUpload(type,file){const rows=await readUpload(file,type);if(!rows.length)throw new Error('No usable data rows found');const result=await fn('hrms-upload',{type,rows,source_file:file.name});$('uploadResult').innerHTML=`<div class="notice"><strong>${esc(type.toUpperCase())} uploaded.</strong> Accepted: ${result.accepted??result.inserted??0} · Skipped: ${result.skipped??0} · Finalized: ${result.finalized??0}</div>`;await loadData()}
async function loadUsers(){const r=await fn('hrms-admin',{action:'list'});$('usersList').innerHTML=`<div class="table-wrap"><table class="table"><thead><tr><th>Username</th><th>Name</th><th>Role</th><th>Employee Code</th><th>Status</th></tr></thead><tbody>${r.data.map(u=>`<tr><td>${esc(u.username)}</td><td>${esc(u.display_name)}</td><td>${esc(u.role)}</td><td>${esc(u.employee_code||'—')}</td><td>${u.active?'Active':'Inactive'}</td></tr>`).join('')}</tbody></table></div>`}
async function loadData(){const month=new Date().toISOString().slice(0,7);const r=await fn('hrms-dashboard',{month});profile=r.profile;employees=r.employees||[];attendance=r.attendance||[];summary=r.summary||{}}
async function boot(){const {data:{session}}=await SB.auth.getSession();if(!session){$('loginView').classList.remove('hidden');$('appView').classList.add('hidden');return}try{await loadData();if(!profile?.active)throw Error('Profile unavailable');$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');$('roleBadge').textContent=profile.role.replaceAll('_',' ').toUpperCase();$('profileMini').innerHTML=`<strong>${esc(profile.display_name)}</strong><small class="muted">${esc(profile.designation||profile.role)}</small>`;$('today').textContent=new Date().toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'});document.querySelectorAll('.admin-only').forEach(x=>x.classList.toggle('hidden',!(profile.role==='admin'||profile.can_upload)));render('dashboard')}catch(e){await SB.auth.signOut();$('loginError').textContent=e.message||'Unable to load HRMS profile.'}}
function render(page){const titles={dashboard:'Dashboard',attendance:'Attendance',employees:'Employees',reports:'MIS Reports',upload:'Data Upload',users:'User Management'};$('pageTitle').textContent=titles[page]||'Dashboard';document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===page));const views={dashboard,attendance:attendancePage,employees:employeesPage,reports,upload:uploadPage,users:usersPage};$('content').innerHTML=(views[page]||dashboard)();if(page==='attendance')bindAttendance();if(page==='reports')$('exportReport').onclick=exportCSV;if(page==='upload')bindUpload();if(page==='users')bindUsers()}
function bindAttendance(){const search=$('employeeSearch');search.oninput=()=>{$('attendanceTable').innerHTML=attendanceTable(employees.filter(e=>JSON.stringify(e).toLowerCase().includes(search.value.toLowerCase())));bindAttendanceButtons()};bindAttendanceButtons()}
function bindAttendanceButtons(){document.querySelectorAll('.calendar-btn').forEach(b=>b.onclick=()=>{const code=b.dataset.code;$('content').innerHTML=employeeCalendar(code);$('backAttendance').onclick=()=>render('attendance');document.querySelectorAll('.att-row').forEach(r=>r.onclick=()=>detailAttendance(code,r.dataset.date))})}
function bindUpload(){document.querySelectorAll('.upload-btn').forEach(b=>b.onclick=async()=>{const f=$(b.dataset.file).files[0];if(!f){$('uploadResult').innerHTML='<div class="notice">Please select a file.</div>';return}b.disabled=true;try{await doUpload(b.dataset.type,f)}catch(e){$('uploadResult').innerHTML=`<div class="notice">Upload failed: ${esc(e.message)}</div>`}b.disabled=false})}
function bindUsers(){$('createUser').onclick=async()=>{try{await fn('hrms-admin',{action:'create',username:$('uUsername').value,email:$('uEmail').value,password:$('uPassword').value,display_name:$('uName').value,role:$('uRole').value});await loadUsers();alert('User created successfully.')}catch(e){alert(e.message)}};loadUsers().catch(e=>{$('usersList').innerHTML=`<div class="notice">${esc(e.message)}</div>`})}
function exportCSV(){const head=['Employee Code','Date','BIO','TOS','Final'];const rows=attendance.map(x=>[x.employee_code,x.attendance_date,x.bio_status||'',x.tos_status||'',x.final_status]);const csv=[head,...rows].map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='hrms-attendance.csv';a.click();URL.revokeObjectURL(a.href)}
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();const btn=$('loginBtn');$('loginError').textContent='';btn.disabled=true;btn.textContent='Signing in…';const {error}=await SB.auth.signInWithPassword({email:emailFor($('username').value.trim()),password:$('password').value});if(error)$('loginError').textContent=error.message||'Invalid username or password.';else await boot();btn.disabled=false;btn.textContent='Sign in'});$('logoutBtn').addEventListener('click',async()=>{await SB.auth.signOut();location.reload()});document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>render(b.dataset.page)));SB.auth.onAuthStateChange((event)=>{if(event==='SIGNED_OUT')location.reload()});boot();