const SUPABASE_URL='https://slsiwqvbdcdcgrkufsln.supabase.co';
const SUPABASE_KEY='sb_publishable_dtWiemrqMQHEXN5SGLGnPw_VGs-ottO';
const SB=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storage:window.localStorage}});
window.HRMS_SB=SB;
const $=id=>document.getElementById(id);
let profile=null, employees=[], rangeStart='', rangeEnd='';
const esc=v=>String(v??'').replace(/[&<>\'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
async function fn(name,body){const{data,error}=await SB.functions.invoke(name,{body});if(error)throw new Error(error.message||'Request failed');if(data?.error)throw new Error(data.error);return data||{}}
window.fn=fn;
function setView(id,show){$(id)?.classList.toggle('hidden',!show)}
function pageTitle(p){return({dashboard:'Dashboard',attendance:'Attendance', 'detailed-attendance':'Detailed Attendance',employees:'Employees',reports:'MIS Reports',upload:'Data Upload',users:'User Management'})[p]||'Dashboard'}
function daysBetween(a,b){const out=[];for(let d=new Date(a+'T00:00:00');d<=new Date(b+'T00:00:00');d.setDate(d.getDate()+1))out.push(d.toISOString().slice(0,10));return out}
function dlabel(d){const x=new Date(d+'T00:00:00');return `${x.toLocaleDateString('en-US',{weekday:'short'})} ${String(x.getDate()).padStart(2,'0')}-${x.toLocaleDateString('en-US',{month:'short'})}-${String(x.getFullYear()).slice(-2)}`}
function shortDate(d){const x=new Date(d+'T00:00:00');return `${x.toLocaleDateString('en-US',{weekday:'short'})} ${x.getDate()}-${x.toLocaleDateString('en-US',{month:'short'})}-${String(x.getFullYear()).slice(-2)}`}
function monthEnd(y,m){return `${y}-${String(m).padStart(2,'0')}-${String(new Date(Date.UTC(y,m,0)).getUTCDate()).padStart(2,'0')}`}
async function latestRange(){const{data,error}=await SB.from('hrms_final_attendance').select('attendance_date').order('attendance_date',{ascending:false}).limit(1).maybeSingle();if(error)throw error;const d=String(data?.attendance_date||'');if(d){const y=d.slice(0,4),m=+d.slice(5,7);rangeStart=`${y}-${String(m).padStart(2,'0')}-01`;rangeEnd=monthEnd(+y,m)}else{const n=new Date();rangeStart=`${n.getFullYear()}-${String(n.getMonth()+1).padStart(2,'0')}-01`;rangeEnd=monthEnd(n.getFullYear(),n.getMonth()+1)}localStorage.setItem('hrmsDateRange',JSON.stringify({start:rangeStart,end:rangeEnd}))}
function loadSavedRange(){try{const x=JSON.parse(localStorage.getItem('hrmsDateRange')||'{}');if(/^\d{4}-\d{2}-\d{2}$/.test(x.start||'')&&/^\d{4}-\d{2}-\d{2}$/.test(x.end||'')){rangeStart=x.start;rangeEnd=x.end;return true}}catch{}return false}
function dateFilter(){return `<div class="date-filter-inner"><b class="date-filter-label">DATE RANGE</b><label>Start <input id="hrmsStartDate" type="date" value="${esc(rangeStart)}"></label><label>End <input id="hrmsEndDate" type="date" value="${esc(rangeEnd)}"></label><button id="applyDateRange" class="primary" type="button">Apply</button><button id="latestMonth" class="ghost" type="button">Latest Month</button></div>`}
function renderFilter(){const f=$('dateFilter');if(f)f.innerHTML=dateFilter()}
async function loadData(){const r=await fn('hrms-dashboard',{start_date:rangeStart,end_date:rangeEnd});profile=r.profile||profile;employees=r.employees||[];window.hrmsDashboard=r;return r}
window.loadData=loadData;
function shell(title,kicker,sub,body){$('pageTitle').textContent=title;$('content').innerHTML=`<div class="hero"><div><div class="eyebrow">${esc(kicker)}</div><h3>${esc(title)}</h3><div class="muted">${esc(sub)}</div></div></div>${body}`}
function dashboard(r){const s=r?.summary||{};shell('Dashboard','OVERVIEW',`Attendance snapshot · ${rangeStart} to ${rangeEnd}`,`<div class="cards"><div class="card"><div class="metric-label">EMPLOYEES</div><div class="metric">${s.employees??employees.length}</div></div><div class="card"><div class="metric-label">PRESENT</div><div class="metric">${s.present??0}</div></div><div class="card"><div class="metric-label">LATE / HALFDAY</div><div class="metric">${(s.late||0)+(s.halfday||0)}</div></div><div class="card"><div class="metric-label">ABSENT / NP</div><div class="metric">${(s.absent||0)+(s.np||0)}</div></div></div><div class="section"><div class="section-title">Workforce</div><div class="table-wrap"><table class="table"><thead><tr><th>Employee ID</th><th>Employee Name</th><th>Designation</th><th>Supervisor</th><th>Process</th></tr></thead><tbody>${employees.slice(0,50).map(e=>`<tr><td>${esc(e.employee_code)}</td><td><strong>${esc(e.employee_name)}</strong></td><td>${esc(e.designation||'—')}</td><td>${esc(e.supervisor_name||e.manager_employee_code||'—')}</td><td>${esc(e.process||'—')}</td></tr>`).join('')||'<tr><td colspan="5">No employees found.</td></tr>'}</tbody></table></div></div>`)}
async function fetchRows(table,select){let out=[];for(let from=0;;from+=1000){const{data,error}=await SB.from(table).select(select).gte('attendance_date',rangeStart).lte('attendance_date',rangeEnd).range(from,from+999);if(error)throw error;out.push(...(data||[]));if(!data||data.length<1000)break}return out}
async function employeeMaster(){const{data,error}=await SB.from('hrms_employee_master').select('employee_code,olm_id,employee_name,designation,supervisor_name,supervisor_employee_id,process,date_of_joining,shift').eq('active',true).order('employee_code');if(error)throw error;return data||[]}
async function attendancePage(){const es=await employeeMaster(),as=await fetchRows('hrms_final_attendance','employee_code,attendance_date,final_status');const m=new Map(as.map(x=>[`${x.employee_code}|${x.attendance_date}`,x.final_status||'']));const ds=daysBetween(rangeStart,rangeEnd);const head=['Sr.No','Employee Code','OLM ID','NAME','DOJ','DESIGNATION','SUPERVISOR NAME','PROCESS','Shift',...ds.map(d=>dlabel(d))];const body=es.map((e,i)=>`<tr><td>${i+1}</td><td>${esc(e.employee_code)}</td><td>${esc(e.olm_id||'')}</td><td><strong>${esc(e.employee_name)}</strong></td><td>${esc(e.date_of_joining||'')}</td><td>${esc(e.designation||'')}</td><td>${esc(e.supervisor_name||'')}</td><td>${esc(e.process||'')}</td><td>${esc(e.shift||'')}</td>${ds.map(d=>`<td class="att-cell">${esc(m.get(`${e.employee_code}|${d}`)||'')}</td>`).join('')}</tr>`).join('');shell('Attendance Format','ATTENDANCE',`Exact ATTENDANCE FORMAT.csv layout · ${rangeStart} to ${rangeEnd}`,`<div class="toolbar"><button id="exportAttendance" class="primary" type="button">Export ATTENDANCE FORMAT.csv</button></div><div class="table-wrap attendance-scroll"><table class="table attendance-table"><thead><tr>${head.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${body||'<tr><td colspan="20">No employees found.</td></tr>'}</tbody></table></div>`);$('exportAttendance').onclick=()=>downloadCSV([head,...es.map((e,i)=>[i+1,e.employee_code,e.olm_id||'',e.employee_name,e.date_of_joining||'',e.designation||'',e.supervisor_name||'',e.process||'',e.shift||'',...ds.map(d=>m.get(`${e.employee_code}|${d}`)||'')])],'ATTENDANCE FORMAT.csv')}
function work(v){if(v==null||v==='')return'';const n=Number(v);return Number.isFinite(n)?`${Math.floor(n/60)}:${String(n%60).padStart(2,'0')}`:String(v)}
async function detailedPage(){const es=await employeeMaster(),ds=daysBetween(rangeStart,rangeEnd);const[as,bs,ts]=await Promise.all([fetchRows('hrms_final_attendance','employee_code,attendance_date,final_status'),fetchRows('hrms_bio_attendance','employee_code,attendance_date,in_time,out_time,work_minutes'),fetchRows('hrms_tos_attendance','employee_code,attendance_date,effective_minutes,login_minutes,status')]);const A=new Map(as.map(x=>[`${x.employee_code}|${x.attendance_date}`,x])),B=new Map(bs.map(x=>[`${x.employee_code}|${x.attendance_date}`,x])),T=new Map(ts.map(x=>[`${x.employee_code}|${x.attendance_date}`,x]));const fixed=['Sr.No','Employee Code','OLM ID','NAME','DOJ','DESIGNATION','SUPERVISOR NAME','PROCESS','Shift'];const top=[...fixed,...ds.map(d=>shortDate(d))],sub=[...fixed,...ds.flatMap(()=>['IN TIME','OUT TIME','WORKING HOURS','TOS','Attendance'])];const rows=es.map((e,i)=>{const v=[i+1,e.employee_code,e.olm_id||'',e.employee_name,e.date_of_joining||'',e.designation||'',e.supervisor_name||'',e.process||'',e.shift||''];ds.forEach(d=>{const k=`${e.employee_code}|${d}`,b=B.get(k)||{},t=T.get(k)||{},a=A.get(k)||{};v.push(b.in_time||'',b.out_time||'',work(b.work_minutes),t.effective_minutes??t.login_minutes??'',a.final_status||'')});return v});const topHtml=fixed.map(h=>`<th rowspan="2">${esc(h)}</th>`).join('')+ds.map(d=>`<th colspan="5">${esc(shortDate(d))}</th>`).join('');const subHtml=ds.flatMap(()=>['IN TIME','OUT TIME','WORKING HOURS','TOS','Attendance']).map(h=>`<th>${h}</th>`).join('');shell('Detailed Attendance Format','ATTENDANCE',`Exact DETAILED ATTENDANCE FORMAT.csv layout · ${rangeStart} to ${rangeEnd}`,`<div class="toolbar"><button id="exportDetailed" class="primary" type="button">Export DETAILED ATTENDANCE FORMAT.csv</button></div><div class="table-wrap detailed-scroll"><table class="table detailed-table"><thead><tr>${topHtml}</tr><tr>${subHtml}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')||'<tr><td colspan="20">No employees found.</td></tr>'}</tbody></table></div>`);$('exportDetailed').onclick=()=>downloadCSV([top,sub,...rows],'DETAILED ATTENDANCE FORMAT.csv')}
async function employeesPage(){const es=await employeeMaster();const h=['Employee ID','OLM ID','Employee Name','Designation','Supervisor Name','Supervisor Employee ID','Process','Date of Joining','Shift'];shell('Employee Master','PEOPLE','Exactly the approved 9-column Employee Master format.',`<div class="table-wrap master-scroll"><table class="table master-table"><thead><tr>${h.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${es.map(e=>`<tr><td>${esc(e.employee_code)}</td><td>${esc(e.olm_id||'')}</td><td><strong>${esc(e.employee_name)}</strong></td><td>${esc(e.designation||'')}</td><td>${esc(e.supervisor_name||'')}</td><td>${esc(e.supervisor_employee_id||'')}</td><td>${esc(e.process||'')}</td><td>${esc(e.date_of_joining||'')}</td><td>${esc(e.shift||'')}</td></tr>`).join('')||'<tr><td colspan="9">No employees found.</td></tr>'}</tbody></table></div>`)}
function reportsPage(r){const a=r?.attendance||[];const by={P:0,LC:0,HD:0,A:0,NP:0};a.forEach(x=>by[x.final_status]=(by[x.final_status]||0)+1);shell('MIS Reports','ANALYTICS',`Final attendance · ${rangeStart} to ${rangeEnd}`,`<div class="cards">${[['P','PRESENT'],['LC','LATE'],['HD','HALFDAY'],['A','ABSENT'],['NP','NOT PUNCHED']].map(x=>`<div class="card"><div class="metric-label">${x[1]}</div><div class="metric">${by[x[0]]}</div></div>`).join('')}</div>`)}
function uploadPage(){shell('Data Upload','DATA INPUT','Only the approved source formats can be uploaded.',`<div class="upload-grid"><div class="card upload-card"><div class="section-title">1. Employee Master</div><div class="muted">CSV only · exact 9-column new format</div><input id="empFile" type="file" accept=".csv"><div id="empFileName" class="file-name">No file selected</div><button class="primary upload-btn" data-type="employees" data-file="empFile" type="button">Upload Employee Master</button></div><div class="card upload-card"><div class="section-title">2. BIO Attendance</div><div class="muted">XLS / XLSX / CSV</div><input id="bioFile" type="file" accept=".xls,.xlsx,.csv"><div id="bioFileName" class="file-name">No file selected</div><button class="primary upload-btn" data-type="bio" data-file="bioFile" type="button">Upload BIO</button></div><div class="card upload-card"><div class="section-title">3. TOS Attendance</div><div class="muted">CSV only</div><input id="tosFile" type="file" accept=".csv"><div id="tosFileName" class="file-name">No file selected</div><button class="primary upload-btn" data-type="tos" data-file="tosFile" type="button">Upload TOS</button></div></div><div id="uploadResult" class="section"></div>`);['empFile','bioFile','tosFile'].forEach(id=>$(id).addEventListener('change',e=>{$(id+'Name').textContent=e.target.files?.[0]?.name||'No file selected'}))}
function parseCSV(text){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(x=>x.trim());if(lines.length<2)return[];const parse=l=>{const a=[];let q=false,c='';for(let i=0;i<l.length;i++){const ch=l[i];if(ch==='\"'){if(q&&l[i+1]==='\"'){c+='\"';i++}else q=!q}else if(ch===','&&!q){a.push(c.trim());c=''}else c+=ch}a.push(c.trim());return a};const h=parse(lines[0]);return lines.slice(1).map(l=>{const v=parse(l),o={};h.forEach((k,i)=>o[k]=v[i]??'');return o})}
function excelTime(v){if(v==null||v==='')return'';if(typeof v==='number'){const total=Math.round(v*1440);return `${String(Math.floor(total/60)%24).padStart(2,'0')}:${String(total%60).padStart(2,'0')}:00`}return String(v).trim()}
function parseBio(data){const wb=XLSX.read(data,{type:'array',cellDates:true});const rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{header:1,defval:''});let ym='2026-08';const period=rows.slice(0,8).flat().join(' '),pm=period.match(/(\d{1,2})-([A-Za-z]{3})-(\d{4})/);if(pm){const mm={Jan:'01',Feb:'02',Mar:'03',Apr:'04',May:'05',Jun:'06',Jul:'07',Aug:'08',Sep:'09',Oct:'10',Nov:'11',Dec:'12'};ym=`${pm[3]}-${mm[pm[2]]||'08'}`}const out=[];for(let i=0;i<rows.length;i++){const r=rows[i];if(String(r[1]??'').trim().toLowerCase()!=='employee code:-')continue;let code='';for(const v of r){const z=String(v??'').trim();if(z&&z.toLowerCase()!=='employee code:-'){code=z;break}}if(!code)continue;const dates=rows[i+1]||[],statuses=rows[i+2]||[],ins=rows[i+3]||[],outs=rows[i+4]||[];for(let c=2;c<dates.length;c++){const ds=String(dates[c]??'').trim(),dm=ds.match(/^(\d{1,2})-/);if(!dm)continue;out.push({employee_code:code,attendance_date:`${ym}-${String(Number(dm[1])).padStart(2,'0')}`,in_time:excelTime(ins[c]),out_time:excelTime(outs[c]),status_source:String(statuses[c]??'').trim()})}}return out}
async function readUpload(file,type){const data=await file.arrayBuffer();return type==='bio'?parseBio(data):parseCSV(new TextDecoder().decode(data))}
window.readUpload=readUpload;
async function doUpload(type,file,btn){const out=$('uploadResult');btn.disabled=true;const old=btn.textContent;btn.textContent='Uploading…';try{const rows=await readUpload(file,type);if(!rows.length)throw Error('No usable data rows found.');if(type==='employees'){const expected=['Employee ID','OLM ID','Employee Name','Designation','Supervisor Name','Supervisor Employee ID','Process','Date of Joining','Shift'];const got=Object.keys(rows[0]).map(x=>x.trim());if(got.length!==9||expected.some((x,i)=>got[i]!==x))throw Error('Invalid Employee Master format. Upload only the new 9-column format in the exact required order.');}const r=await fn('hrms-upload',{type,rows,source_file:file.name});out.innerHTML=`<div class="notice"><strong>${esc(type.toUpperCase())} uploaded successfully.</strong> Accepted: ${r.accepted??r.inserted??0} · Skipped: ${r.skipped??0} · Finalized: ${r.finalized??0}</div>`;await loadData();if(type==='employees')employees=r.employees||employees}catch(e){out.innerHTML=`<div class="error upload-error">${esc(e.message||'Upload failed.')}</div>`}finally{btn.disabled=false;btn.textContent=old}}
function downloadCSV(rows,name){const csv=rows.map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function route(p){document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===p));$('pageTitle').textContent=pageTitle(p);if(p==='upload'||p==='users')$('dateFilter').style.display='none';else{$('dateFilter').style.display='block';renderFilter()}$('content').innerHTML='<div class="notice">Loading…</div>';try{if(p==='dashboard')dashboard(await loadData());else if(p==='attendance')await attendancePage();else if(p==='detailed-attendance')await detailedPage();else if(p==='employees')await employeesPage();else if(p==='reports')reportsPage(await loadData());else if(p==='upload')uploadPage();else if(p==='users')await usersPage()}catch(e){console.error(e);$('content').innerHTML=`<div class="error upload-error">Unable to load ${esc(pageTitle(p))}: ${esc(e.message||e)}</div>`}}
async function usersPage(){const r=await fn('hrms-admin',{action:'list'});const rows=r.users||r.data||[];shell('User Management','ADMINISTRATION','Role-based access management.',`<div class="card"><div class="section-title">Create User</div><div class="toolbar"><input id="uUsername" placeholder="Username"><input id="uEmail" placeholder="Email"><input id="uPassword" type="password" placeholder="Password (min 6)"><input id="uName" placeholder="Display name"><select id="uRole"><option value="viewer">MIS / Viewer</option><option value="manager">Manager</option><option value="team_leader">Team Leader</option><option value="tele_sales_executive">Tele Sales Executive</option><option value="uploader">Uploader</option><option value="admin">Admin</option></select><button id="createUser" class="primary" type="button">Create User</button></div></div><div class="section"><div class="table-wrap"><table class="table"><thead><tr><th>Username</th><th>Name</th><th>Role</th><th>Employee Code</th><th>Status</th></tr></thead><tbody>${rows.map(u=>`<tr><td>${esc(u.username)}</td><td>${esc(u.display_name)}</td><td>${esc(u.role)}</td><td>${esc(u.employee_code||'—')}</td><td>${u.active?'Active':'Inactive'}</td></tr>`).join('')||'<tr><td colspan="5">No users found.</td></tr>'}</tbody></table></div></div>`);$('createUser').onclick=async()=>{try{const r=await fn('hrms-admin',{action:'create',username:$('uUsername').value,email:$('uEmail').value,password:$('uPassword').value,display_name:$('uName').value,role:$('uRole').value});alert(r.message||'User created');await route('users')}catch(e){alert(e.message)}}}
async function boot(){const{data:{session}}=await SB.auth.getSession();if(!session){setView('loginView',true);setView('appView',false);return}try{if(!loadSavedRange())await latestRange();await loadData();setView('loginView',false);setView('appView',true);$('roleBadge').textContent=(profile?.role||'HRMS').replaceAll('_',' ').toUpperCase();$('profileMini').innerHTML=`<strong>${esc(profile?.display_name||profile?.username||'User')}</strong><small class="muted">${esc(profile?.designation||profile?.role||'')}</small>`;$('today').textContent=new Date().toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'});document.querySelectorAll('.admin-only').forEach(x=>x.classList.toggle('hidden',!(profile?.role==='admin'||profile?.can_upload)));renderFilter();route('dashboard')}catch(e){setView('loginView',false);setView('appView',true);$('content').innerHTML=`<div class="error upload-error">${esc(e.message||'Unable to load HRMS.')}</div>`}}
window.boot=boot;
document.addEventListener('click',e=>{const nav=e.target.closest('.nav-item');if(nav){e.preventDefault();e.stopPropagation();route(nav.dataset.page);return}const b=e.target.closest('.upload-btn');if(b){e.preventDefault();e.stopPropagation();const f=$(b.dataset.file)?.files?.[0];if(!f){$('uploadResult').innerHTML='<div class="error upload-error">Please select a file first.</div>';return}doUpload(b.dataset.type,f,b);return}if(e.target.closest('#applyDateRange')){const s=$('hrmsStartDate')?.value,t=$('hrmsEndDate')?.value;if(!s||!t||s>t){alert('Please select a valid Start and End date.');return}rangeStart=s;rangeEnd=t;localStorage.setItem('hrmsDateRange',JSON.stringify({start:rangeStart,end:rangeEnd}));route(document.querySelector('.nav-item.active')?.dataset.page||'dashboard');return}if(e.target.closest('#latestMonth')){latestRange().then(()=>route(document.querySelector('.nav-item.active')?.dataset.page||'dashboard')).catch(x=>alert(x.message));return}if(e.target.closest('#topLogout')){SB.auth.signOut();return}},false);
document.addEventListener('submit',async e=>{if(e.target.id!=='loginForm')return;e.preventDefault();const err=$('loginError'),btn=$('loginBtn');err.textContent='';btn.disabled=true;btn.textContent='Signing in…';try{const raw=String($('username').value||'').trim().toLowerCase(),email=raw==='admin'?'srp8046@gmail.com':(raw.includes('@')?raw:`${raw}@login.leeway.local`);const{data,error}=await SB.auth.signInWithPassword({email,password:String($('password').value||'')});if(error)throw error;if(!data?.session)throw Error('Login session could not be created.');await boot()}catch(x){err.textContent=x.message||'Unable to sign in.'}finally{btn.disabled=false;btn.textContent='Sign in'}},false);
SB.auth.onAuthStateChange((event)=>{if(event==='SIGNED_OUT'){setView('appView',false);setView('loginView',true)}else if(event==='SIGNED_IN')setTimeout(()=>boot(),0)});
document.addEventListener('DOMContentLoaded',boot);