(function(){
  const KEY='hrmsDateRange',PAGE_KEY='hrmsReturnPage';
  const pad=n=>String(n).padStart(2,'0'),d=new Date();
  const saved=JSON.parse(localStorage.getItem(KEY)||'null')||{};
  let start=saved.start||`${d.getFullYear()}-${pad(d.getMonth()+1)}-01`,end=saved.end||`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
  function build(){const h=document.getElementById('dateFilter');if(!h)return;h.style.display='block';h.innerHTML=`<div class="date-filter-inner"><b class="date-filter-label">DATE RANGE</b><label>Start <input id="hrmsStartDate" type="date" value="${start}"></label><label>End <input id="hrmsEndDate" type="date" value="${end}"></label><button id="applyDateRange" class="primary">Apply</button><button id="clearDateRange" class="ghost">Current Month</button></div>`;document.getElementById('applyDateRange').onclick=apply;document.getElementById('clearDateRange').onclick=()=>{const x=new Date();document.getElementById('hrmsStartDate').value=`${x.getFullYear()}-${pad(x.getMonth()+1)}-01`;document.getElementById('hrmsEndDate').value=`${x.getFullYear()}-${pad(x.getMonth()+1)}-${pad(x.getDate())}`;apply()}}
  function apply(){const s=document.getElementById('hrmsStartDate').value,e=document.getElementById('hrmsEndDate').value;if(!s||!e||s>e){alert('Please select a valid Start and End date.');return}start=s;end=e;localStorage.setItem(KEY,JSON.stringify({start,end}));const a=document.querySelector('.nav-item.active');if(a)sessionStorage.setItem(PAGE_KEY,a.dataset.page||'dashboard');location.reload()}
  const nativeFetch=window.fetch.bind(window);window.fetch=async function(input,init){try{const u=typeof input==='string'?input:input?.url||'';if(u.includes('/functions/v1/hrms-dashboard')&&init?.body){const b=JSON.parse(init.body);b.start_date=start;b.end_date=end;init={...init,body:JSON.stringify(b)}}}catch(e){}return nativeFetch(input,init)};
  const css=document.createElement('style');css.textContent='.date-filter{display:block!important;padding:0 24px!important}.date-filter-inner{display:flex;align-items:end;gap:12px;padding:12px 14px;margin:0 0 4px;border:1px solid rgba(128,128,128,.22);border-radius:12px;background:var(--card,#fff);box-shadow:0 2px 10px rgba(0,0,0,.05);flex-wrap:wrap}.date-filter-label{font-size:11px;letter-spacing:.08em;opacity:.7}.date-filter-inner label{font-size:11px;font-weight:700;display:flex;flex-direction:column;gap:5px}.date-filter-inner input{height:36px;padding:0 10px;border:1px solid rgba(128,128,128,.35);border-radius:8px;background:transparent;color:inherit}.date-filter-inner button{height:36px;padding:0 14px;cursor:pointer}@media(max-width:700px){.date-filter{padding:0 12px!important}.date-filter-inner{align-items:stretch}.date-filter-inner label{flex:1;min-width:130px}.date-filter-inner button{flex:1}}';document.head.appendChild(css);
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',build);else build();
  const page=sessionStorage.getItem(PAGE_KEY);if(page){sessionStorage.removeItem(PAGE_KEY);setTimeout(()=>document.querySelector(`.nav-item[data-page="${page}"]`)?.click(),1000)}
})();