(function(){
  const KEY='hrmsDateRange';
  const saved=JSON.parse(localStorage.getItem(KEY)||'null')||{};
  const pad=n=>String(n).padStart(2,'0');
  const today=new Date();
  const defaultEnd=`${today.getFullYear()}-${pad(today.getMonth()+1)}-${pad(today.getDate())}`;
  const defaultStart=`${today.getFullYear()}-${pad(today.getMonth()+1)}-01`;
  let start=saved.start||defaultStart,end=saved.end||defaultEnd;
  function style(){if(document.getElementById('dateFilterStyle'))return;const s=document.createElement('style');s.id='dateFilterStyle';s.textContent=`.date-filter{padding:0 24px}.date-filter-inner{display:flex;align-items:end;gap:12px;padding:12px 14px;margin:0 0 4px;border:1px solid rgba(128,128,128,.18);border-radius:12px;background:var(--card,#fff);box-shadow:0 2px 10px rgba(0,0,0,.04);flex-wrap:wrap}.date-filter-label{font-size:11px;font-weight:800;letter-spacing:.08em;margin-right:4px;opacity:.7}.date-filter-inner label{font-size:11px;font-weight:700;display:flex;flex-direction:column;gap:5px}.date-filter-inner input{height:36px;padding:0 10px;border:1px solid rgba(128,128,128,.3);border-radius:8px;background:transparent}.date-filter-inner button{height:36px;padding:0 14px}.date-filter-inner .ghost{border:1px solid rgba(128,128,128,.25);background:transparent}@media(max-width:700px){.date-filter{padding:0 12px}.date-filter-inner{align-items:stretch}.date-filter-label{width:100%}.date-filter-inner label{flex:1;min-width:130px}.date-filter-inner button{flex:1}}`;document.head.appendChild(s)}
  function build(){const host=document.getElementById('dateFilter');if(!host)return;style();host.innerHTML=`<div class="date-filter-inner"><span class="date-filter-label">DATE RANGE</span><label>Start <input id="hrmsStartDate" type="date" value="${start}"></label><label>End <input id="hrmsEndDate" type="date" value="${end}"></label><button id="applyDateRange" class="primary">Apply</button><button id="clearDateRange" class="ghost">Current Month</button></div>`;document.getElementById('applyDateRange').onclick=async()=>{const s=document.getElementById('hrmsStartDate').value,e=document.getElementById('hrmsEndDate').value;if(!s||!e||s>e){alert('Please select a valid Start and End date.');return}start=s;end=e;localStorage.setItem(KEY,JSON.stringify({start,end}));await refresh()};document.getElementById('clearDateRange').onclick=async()=>{const d=new Date();start=`${d.getFullYear()}-${pad(d.getMonth()+1)}-01`;end=`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;localStorage.setItem(KEY,JSON.stringify({start,end}));build();await refresh()}}
  async function refresh(){try{await window.loadData();if(typeof window.render==='function')window.render('dashboard')}catch(e){console.error(e)}}
  const wait=setInterval(()=>{if(window.SB&&document.getElementById('dateFilter')){clearInterval(wait);const original=window.SB.functions.invoke.bind(window.SB.functions);window.SB.functions.invoke=async(name,opts={})=>{if(name==='hrms-dashboard'){const body=Object.assign({},opts.body||{},{start_date:start,end_date:end});opts=Object.assign({},opts,{body})}return original(name,opts)};build();refresh()}},100);
})();